# Automation Build for AndroidStudio Projects.
# Based on Ivy structure this pipeline yml is configured.
# Below configurations are based on build server setup

#Option variables based on the project SDK
#variables:
#  ANDROID_COMPILE_SDK: "25"
#  ANDROID_BUILD_TOOLS: "24.0.0"
#  ANDROID_SDK_TOOLS: "24.4.1"

before_script:

#Build Server SDK path Locations

  - export ANDROID_HOME=:/home/gitlab-runner/android-sdk-linux
  - export PATH=$PATH:=:/home/gitlab-runner/android-sdk-linux/platform-tools/
  - chmod +x ./gradlew
 
# KeyStore path for Signed Apk generation
 
  - export keystorepath="/home/ubuntu/Ivykeystore/ivy.keystore"
  - export keyalias="envisionmobility"
  - export googleapikey="AIzaSyA7mpkDBVpJtZ_lrYk4jPdb70cfTrSKTt0"
  - export keystoreusername="envision"
  - export keystorepassword="envision**321"

# Userdefined Variables for output path folder creation
  
  - export commitid=$(git rev-list --count HEAD)
  - export shaid=$(git rev-parse HEAD)
  - echo ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${commitid}_${CI_COMMIT_SHA:0:8}
  - mkdir -p $ANDROID_HOME/licenses
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
##after_script:
 
#GitLab runner path details

##  - export build_path="/home/gitlab-runner/builds/081c14b4/0/IvyProjects"
##  - export source_path="ivycpg/build/outputs/apk/release"
##  - export output_path="/opt/buildoutputs"
##  - export commitid=$(git rev-list --count HEAD)
##  - cd "${output_path}"
##  - mkdir -p "${CI_PROJECT_NAME}"_"${CI_COMMIT_REF_NAME}"
# - cd "${CI_PROJECT_NAME}"_"${CI_COMMIT_REF_NAME}"
# - mkdir -p "${CI_PROJECT_NAME}"_"${CI_COMMIT_REF_NAME}"_"${commitid}"_"${CI_COMMIT_SHA:0:8}"
# - cp $build_path/$CI_PROJECT_NAME/$source_path/ivycpg-release.apk $output_path/${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}/${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${commitid}_${CI_COMMIT_SHA:0:8}/ivycpg-release.apk
# - cp $build_path/$CI_PROJECT_NAME/$source_path/* $output_path/${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}/${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${commitid}_${CI_COMMIT_SHA:0:8}/
##  - cd $build_path/$CI_PROJECT_NAME/$source_path
# - zip -r $output_path/${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}/${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${commitid}_${CI_COMMIT_SHA:0:8}.zip /*
 ## - zip -r $output_path/${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}/${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${commitid}_${CI_COMMIT_SHA:0:8}.zip ivycpg-release.apk
# - mkdir -p "${output_path}"/"${CI_PROJECT_NAME}"_"${CI_COMMIT_REF_NAME}"/"${CI_PROJECT_NAME}"_"${CI_COMMIT_REF_NAME}"_"${commitid}"_"${CI_COMMIT_SHA:0:8}"
# - (if [ "$(bin/goimports -d src/smarpshare/)" == "" ]; then echo "Good format"; else echo "Bad format"; exit 33; fi);
# - (if [ -d "${output_path}"/"${CI_PROJECT_NAME}"_"${CI_COMMIT_REF_NAME}"/"${CI_PROJECT_NAME}"_"${CI_COMMIT_REF_NAME}"_"${commitid}"_"${CI_COMMIT_SHA:0:8}")" == ""]; then mkdir -p "${output_path}"/"${CI_PROJECT_NAME}"_"${CI_COMMIT_REF_NAME}"/"${CI_PROJECT_NAME}"_"${CI_COMMIT_REF_NAME}"_"${commitid}"_"${CI_COMMIT_SHA:0:8}"; else echo "Folder Exist"; exit 33; fi);
# - if [ -d ""${output_path}"/"${CI_PROJECT_NAME}"_"${CI_COMMIT_REF_NAME}"/"${CI_PROJECT_NAME}"_"${CI_COMMIT_REF_NAME}"_"${commitid}"_"${CI_COMMIT_SHA:0:8}"" ]; 
#  then 
#  echo "Directory DB_handouts found" 
#  else 
#  mkdir -m -p "${output_path}"/"${CI_PROJECT_NAME}"_"${CI_COMMIT_REF_NAME}"/"${CI_PROJECT_NAME}"_"${CI_COMMIT_REF_NAME}"_"${commitid}"_"${CI_COMMIT_SHA:0:8}" 
#  fi
# - if [ -d ""${output_path}"/"${CI_PROJECT_NAME}"_"${CI_COMMIT_REF_NAME}"/"${CI_PROJECT_NAME}"_"${CI_COMMIT_REF_NAME}"_"${commitid}"_"${CI_COMMIT_SHA:0:8}"" ]; then echo "Directory DB_handouts found" else mkdir -p "${output_path}"/"${CI_PROJECT_NAME}"_"${CI_COMMIT_REF_NAME}"/"${CI_PROJECT_NAME}"_"${CI_COMMIT_REF_NAME}"_"${commitid}"_"${CI_COMMIT_SHA:0:8}" fi
 

stages:
  - build

build:
  stage: build
  script:
    - ./gradlew clean
    - ./gradlew assemblerelease
